config = {
    'experiment_num': 50,
    'confounds_num': 25,
    'gen_batch_num': 128,
    'z_batch_num': 128,
    'or_batch_num': 128,
    'selection_batch_num': 128,
    'estimator_batch_num': 128,
    'selection_dim_in': 25 + 2,
    'selection_dim_latent': 1,
    'selection_dim_out': 10,
    'selection_layer_num': 2,
    'regression_dim_in': 25 + 1,
    'regression_dim_out': 10,
    'regression_dim_latent': 1,
    'regression_layer_num': 2,
    'or_dim_in': 25 + 2,
    'or_dim_out': 10,
    'or_dim_latent': 1,
    'or_layer_num': 2,
    'z_dim_in': 25 + 1,
    'z_dim_out': 10,
    'z_layer_num': 2,
    'generator_dim_in': 25,
    'generator_dim_out': 10,
    'generator_dim_latent': 1,
    'generator_layer_num': 2,
    'generator_lr': 0.03,
    'generator_wd': 0.01,
    'generator_max_iter': 10,
    'generator_threshold': 0.1,
    'generator_epochs': 100,
    'q_epochs': 100,
    'z_epochs': 100,
    'or_epochs': 100,
    'estimator_epochs': 100,
    'selection_epochs': 100,
    'selection_lr': 0.03,
    'selection_wd': 0.01,
    'selectionnet_lr': 0.03,
    'selectionnet_wd': 0.01,
    'estimator_lr': 0.03,
    'estimator_wd': 0.01,
    'q_lr': 0.03,
    'q_wd': 0.01,
    'z_lr': 0.03,
    'z_wd': 0.01,
    'or_lr': 0.03,
    'or_wd': 0.01,
    'ipm_weight': 0.001,
}
